/// Flutter icons CustomNotification
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomNotification
///      fonts:
///       - asset: fonts/CustomNotification.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomNotification {
  CustomNotification._();

  static const _kFontFam = 'CustomNotification';
  static const String? _kFontPkg = null;

  static const IconData logout = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationcustom = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
